
ptOne: ptOne.o
	g++ -o ptOne ptOne.o

ptOne.o : ptOne.cpp
	g++ -c ptOne.cpp

clean:
	rm -f ptOne.o ptOne


# OBJS = ptOne.o

# ptOne: $(OBJS)
# 	g++ -o ptOne $(OBJS)

# # ptOne.o : ptOne.cpp

# .PHONY: clean
# clean:
# 	rm -f ptOne $(OBJS)

